[package]
name = "rustnpp"
version = "1.0.0"
authors = ["ნიკა <nika.begiashvili@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc="*"
winapi = { version = "0.3.9", features = ["winuser"] }
lazy_static = "1.4.*"